Traceback (most recent call last):
  File "H:\HadiSadoghiYazdi\Circuit\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
    ~~~~~~~~~^
        nb,
        ^^^
    ...<4 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "H:\HadiSadoghiYazdi\Circuit\Lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "H:\HadiSadoghiYazdi\Circuit\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Program Files\Python313\Lib\asyncio\base_events.py", line 721, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "H:\HadiSadoghiYazdi\Circuit\Lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
        cell, index, execution_count=self.code_cells_executed + 1
    )
  File "H:\HadiSadoghiYazdi\Circuit\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "H:\HadiSadoghiYazdi\Circuit\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import PySpice.Logging.Logging as Logging
logger = Logging.setup_logging()
from PySpice.Spice.Netlist import Circuit
circuit = Circuit('Voltage Divider Circuit') # Create a new circuit
# Add components to the circuit
circuit.V('V1', 'A', circuit.gnd, 5@u_V)  # Voltage source VA = 5V  
circuit.R('R1', 'A', '1', 2 * 1@u_kOhm)
circuit.R('R2', '1', 'B', 1@u_kOhm)
circuit.R('R3', 'B', 'C', 1@u_kOhm)
circuit.R('R4', 'C', 'Vout', 1@u_kOhm)
circuit.R('R5', 'Vout', circuit.gnd, 2 * 1@u_kOhm)
circuit.R('R6', '1', circuit.gnd, 2 * 1@u_kOhm)
circuit.R('R7', 'B', circuit.gnd, 2 * 1@u_kOhm)  
circuit.R('R8', 'C', circuit.gnd, 2 * 1@u_kOhm)  
# Create a simulator object
simulator = circuit.simulator(temperature=25, nominal_temperature=25)
analysis = simulator.operating_point()  
for node in analysis.nodes.values():
    print('Node {}: {:5.4f} V'.format(str(node), float(node))) # print Vout 
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Cell [1;32mIn[6], line 6[0m
[0;32m      4[0m circuit [38;5;241m=[39m Circuit([38;5;124m'[39m[38;5;124mVoltage Divider Circuit[39m[38;5;124m'[39m) [38;5;66;03m# Create a new circuit[39;00m
[0;32m      5[0m [38;5;66;03m# Add components to the circuit[39;00m
[1;32m----> 6[0m circuit[38;5;241m.[39mV([38;5;124m'[39m[38;5;124mV1[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mA[39m[38;5;124m'[39m, circuit[38;5;241m.[39mgnd, [38;5;241m5[39m[38;5;129m@u_V[39m)  [38;5;66;03m# Voltage source VA = 5V  [39;00m
[0;32m      7[0m circuit[38;5;241m.[39mR([38;5;124m'[39m[38;5;124mR1[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mA[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124m1[39m[38;5;124m'[39m, [38;5;241m2[39m [38;5;241m*[39m [38;5;241m1[39m[38;5;129m@u_kOhm[39m)
[0;32m      8[0m circuit[38;5;241m.[39mR([38;5;124m'[39m[38;5;124mR2[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124m1[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mB[39m[38;5;124m'[39m, [38;5;241m1[39m[38;5;129m@u_kOhm[39m)

[1;31mNameError[0m: name 'u_V' is not defined

